services:
  pg:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "spider"
      POSTGRES_DB: "spiderdb"
      PGDATA: "/var/lib/postgresql/18/docker"
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spider -d spiderdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "spiderpguser@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "interseptor"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres:
    driver: bridge
